### ISSUE TITLE
timeout with HTTPS

### ISSUE THREAD

**Issue by mikeshaker** [feross/simple-get#47]
I noticed if the request url is https timeout doesn't work, see example below
```javascript
const get = require('simple-get')
 
const opts = {
  url: 'http://example.com',
  timeout: 10
}
 
get(opts, function (err, res) {
  console.log('HTTP', err);
})
})
// result
// HTTP Error: Request timed out
//     at ClientRequest.req.on (/home/runner/node_modules/simple-get/index.js:67:8)
//     at ClientRequest.emit (events.js:180:13)
//     at Socket.emitRequestTimeout (_http_client.js:641:42)
//     at Object.onceWrapper (events.js:272:13)
//     at Socket.emit (events.js:180:13)
//     at Socket._onTimeout (net.js:396:8)
//     at ontimeout (timers.js:466:11)
//     at tryOnTimeout (timers.js:304:5)
//     at Timer.listOnTimeout (timers.js:267:5)
 
const opts2 = {
  url: 'https://example.com',
  timeout: 10
}
 
get(opts2, function (err, res) {
  console.log('HTTPS', err);
})
// result
//HTTPS null
```

**Comment by bendrucker** [comment]
Can't reproduce. Just ran this and got a socket timeout as expected:

```js
require('simple-get')({url: 'https://google.com', timeout: 1}, console.log.bind(console))
```

**Comment by mikeshaker** [comment]
here is demo , am I missing something ?
https://repl.it/@MikeShaker/NewColossalRectangle

**Comment by bendrucker** [comment]
That website is super flaky for me, republished a simpler example here, still not reproducible:

https://runkit.com/bendrucker/5c50a6be8b22250011f20960
